[package]
name = "rose"
version = "0.1.0"
edition = "2021"
authors = ["Sokyoei"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = ["axum_learn", "rust"]
